project_id = "mrkcgfsbdcukufgwvjap"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[functions.analyze-image]
verify_jwt = false

[functions.search-content]
verify_jwt = false

[auth]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[storage]
enabled = true

[storage.image_transformation]
enabled = true